### ISSUE TITLE
Server side crash

### ISSUE THREAD

**Issue by scalda** [LatvianModder/XPTeleporters#1]
Hi i have just updated xpteleporters added the lib aswell, all works fine client side i don't get any crashes.

but it crashes my server when i load it up please find the crash report attached.

[http://pastebin.com/SJHrrtWB](url)

regards

scalda

**Comment by O13SC3N3** [comment]
Similar when placing XPTeleporter down
forget 1614
Mod Version 1.27
Lib Version 1.0.17.3
http://pastebin.com/raw/i5YsdDPe
