### ISSUE TITLE
Client crashes when right clicking on XPTeleport with Link card

### ISSUE THREAD

**Issue by ghost** [LatvianModder/XPTeleporters#2]
When right clicking on XPTeleporter with a configured Link card, client crashes immediately. Below is client log and also crash-report. 1.x.x version was working well but I had an issue as it disables NEI on inventory screen and switches to regular Minecraft creative tab anytime after teleporting inter dimensionally. However this is not the pressing 'O' key accidentally kinds, the screen won't fix until re-login. I know FTBLib is still work in progress but I appreciate if you could look into the issue. Thank you.

http://pastebin.com/E7H1D9Xh
http://pastebin.com/TDCXSmwC

**Comment by ghost** [comment]
Oh I just found out combination of XPT 1.2.7 with FTBLib 1.0.16 works perfectly fine with no visible issues. Therefore the latest FTBLib may be missing some codes?
By the way I'd appreciate if implementing a configurable option that teleporting by just stepping on without pressing shift is possible... Thanks!

**Comment by LatvianModder** [comment]
Yeah, the latest FTBLib had some code changes, so it didnt really work.. Once I finish the 1.8.9 update, I will update the rest of my mods in 1.7.10

**Comment by ghost** [comment]
I see I'm stoked about update so FTBUtilities can also work on my server together with XPT. Thank you.
